# testConditionalGANPytorch1  
Andrew E. Davidson aedavids@ucsc.edu 8/29/24  

Copyright (c) 2020-2023, Regents of the University of California All rights reserved.   https://polyformproject.org/licenses/noncommercial/1.0.0

AIM: create a simple GAN that is easy to test our basic framework

generate y = x^2

ref: 
- chapter 6. in Generative Advisarial Networks with Python  
    this does not work. Keras/tensor flow version issues?  
    re-write example using pytorch

- [pytorch doc](https://pytorch.org/docs/stable/index.html)

In [2]:
import ipynbname
import matplotlib.pyplot as plt

from numpy import hstack
from numpy import zeros
from numpy import ones
from numpy.random import rand
from numpy.random import randn
import os

# by default keras use tensorflow as backend
import torch
print(f'torch.__version__: {torch.__version__}')

from torch import nn
torch.manual_seed(0) # Set for testing purposes, please do not change!

notebookName = ipynbname.name()
notebookPath = ipynbname.path()
notebookDir = os.path.dirname(notebookPath)

outDir = f'{notebookDir}/{notebookName}.out'
imgOut = f'{outDir}/img'
print(f'imgOut:\n{imgOut}')

torch.__version__: 2.5.1.post102
imgOut:
/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/jupyterNotebooks/elife/gan/testConditionalGAN_pytorch_1.out/img


## Create models

In [ ]:
def class ParabolaDiscriminator( nn.Module ):
    def __init__( self, inputSize : int ):
        super().__init()__

        # keras
        # model = Sequential()
    	# model.add(Dense(25, activation='relu', kernel_initializer='he_uniform', input_dim=n_inputs))
    	# model.add(Dense(1, activation='sigmoid'))
        
        self.model = nn.Sequential(
            nn.Linear(n_inputs, aedwip 25),
            nn.ReLU(),
            nn.Linear(aedwip[ 25, 1),
            nn.Sigmoid()
        )
        
        # Initialize weights
        init.kaiming_uniform_(self.model[0].weight, nonlinearity='relu')
        init.zeros_(self.model[0].bias)
        init.kaiming_uniform_(self.model[2].weight, nonlinearity='sigmoid')
        init.zeros_(self.model[2].bias)

    def forward( self ):
        ret = self.model( x )
        return ret

In [ ]:
def class ParabolaGenerator( nn.Module ):
    def __init__( self, aedwip ) :
        super().__init()

        # keras
        # model.add(Dense(15, activation='relu', kernel_initializer='he_uniform', input_dim=latent_dim))
        # model.add(Dense(n_outputs, activation='linear'))
        
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 15),
            nn.ReLU(),
            nn.Linear(15, n_outputs),
            nn.Linear()
        )
        # Initialize weights
        init.kaiming_uniform_(self.model[0].weight, nonlinearity='relu')
        init.zeros_(self.model[0].bias)
        init.kaiming_uniform_(self.model[2].weight, nonlinearity='linear')
        init.zeros_(self.model[2].bias)

    def forward( self, noise : torch.Tensor ):
        '''
            noise should be the value returned by generateLatentPoints()
        '''
        ret = self.generator( noise )
        return ret

## Data Utilities
function to generate real and fake tensors

In [25]:
def generateRealSamples( n : int ) -> tuple[torch.Tensor, torch.Tensor] :
    '''
    generate n real parabola samples with class labels

    Returns 2 Tensor
        X, y

        y = 1, ie real
    '''
    # generate inputs in range [-0.5, 0.5]
    X1 = rand(n) - 0.5
    
    # generate outputs X^2
    X2 = X1 * X1
    
    # stack arrays
    X1 = X1.reshape(n, 1)
    X2 = X2.reshape(n, 1)
    X = hstack((X1, X2))
    
    # generate class labels
    y = ones((n, 1))
    
    retX = torch.Tensor( X )
    rety = torch.Tensor( y)
    
    return retX, rety

def testGenerateRealSamples() :
    X, y = generateRealSamples( n = 5 ) 
    print( f'X.shape: {X.shape} rank : {len(X.shape)} num elements : {X.numel()}' )
    print( X )

    print( f'\ny.shape: {y.shape} rank : {len(y.shape)} num elements : {y.numel()}' )
    print ( y) 

testGenerateRealSamples()

X.shape: torch.Size([5, 2]) rank : 2 num elements : 10
tensor([[0.4396, 0.1932],
        [0.3691, 0.1363],
        [0.0550, 0.0030],
        [0.1312, 0.0172],
        [0.3500, 0.1225]])

y.shape: torch.Size([5, 1]) rank : 2 num elements : 5
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [19]:
def generateLatentPoints(latentDimensions : int = 5, 
                         n : int = 100) -> torch.Tensor :
    '''
    generate points in latent space as input for the generator

    latentDimensions:
        the number of dimensions for the generator's input vector

    n the number of vectors to generate

    returns a tensor
    '''
    # generate points in the latent space
    xInput = randn(latentDimensions * n)
    
    # reshape into a batch of inputs for the network
    xInput = xInput.reshape(n, latentDimensions)
    
    ret = torch.Tensor( xInput )
    
    return ret

def testGenerateLatentPoints():
    tglp = generateLatentPoints(latentDimensions=5, n=3 )
    print( tglp )
    print( tglp.shape )

testGenerateLatentPoints()

tensor([[-0.1704, -1.5000,  0.2586, -0.0029,  0.1819],
        [-1.2354, -1.1589,  0.1760,  0.7779,  0.1394],
        [-0.3684,  0.4913,  1.8745, -1.6211, -1.2304]])
torch.Size([3, 5])


In [ ]:
aedwip
def generateFakeSamples(generator : ParabolaGAN_Generator, latentDimensions, n):
    '''
    use the generator to generate n fake examples, with class labels
    '''
    
	# generate points in latent space
	x = generateLatentPoints(latentDimensions, n)
	# predict outputs
	aedwip silent=0
	retx = generator.predict(x, verbose=silent)
	# create class labels

	y = zeros((n, 1))
    rety = torch.Tensor( y )

	return retX, rety

## Train Model

In [ ]:
# create a discrimanator
discriminatorModel = ParabolaGAN_Discriminator( inputSize=2 )
# define the cost function
discriminatorCriterion = nn.BCELoss()

# use stochastic gradient decent
# keras
# 	discrModel.compile(loss='binary_crossentropy', optimizer='adam', 
# metrics=['accuracy'])

learningRate = 0.01
discriminatorOptimizer = torch.optim.adam( discriminatorModel.parameters, 
                                          lr=learningRate )

# define the number of training loops
numEpochs = aedwip
for t in range( numEpochs ) :

    # forward propagation
    # get a prediction
    yHat = discriminatorModel( X )
    discriminatorLoss = discriminatorCriterion( yHat, y)

    # backward propagation
    discriminatorOptimizer.zero_grad()
    discriminatorLoss.backward()

    # update the parameters
    discriminatorOptimizer.step()
    